version: '3.7'

services:
  rundown:
    container_name: rundown
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: yarn start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - rundowndb

  rundowndb:
    container_name: rundowndb
    image: postgres:13-alpine
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    networks:
      - webnet
    ports:
      - 8080:8080
networks:
  webnet:
volumes:
  pgdata:
